In [1]:
import pandas as pd
import numpy as np

## Importing data

In [2]:
data = pd.read_csv("corona_tested_individuals_ver_006.english.csv")

C:\Users\ritvi\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py:3169: DtypeWarning: Columns (1,2,3,4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278848 entries, 0 to 278847
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   test_date            278848 non-null  object
 1   cough                278848 non-null  object
 2   fever                278848 non-null  object
 3   sore_throat          278848 non-null  object
 4   shortness_of_breath  278848 non-null  object
 5   head_ache            278848 non-null  object
 6   corona_result        278848 non-null  object
 7   age_60_and_above     278848 non-null  object
 8   gender               278848 non-null  object
 9   test_indication      278848 non-null  object
dtypes: object(10)
memory usage: 21.3+ MB


In [4]:
data.columns

Index(['test_date', 'cough', 'fever', 'sore_throat', 'shortness_of_breath',
       'head_ache', 'corona_result', 'age_60_and_above', 'gender',
       'test_indication'],
      dtype='object')

## Preprocessing

#### Since test_data is not needed for covid prediction, removing that column

In [5]:
data.drop('test_date', inplace=True, axis=1)

In [6]:
data.columns

Index(['cough', 'fever', 'sore_throat', 'shortness_of_breath', 'head_ache',
       'corona_result', 'age_60_and_above', 'gender', 'test_indication'],
      dtype='object')

In [7]:
data.head()

cough fever sore_throat shortness_of_breath head_ache corona_result  \
0     0     0           0                   0         0      negative   
1     1     0           0                   0         0      negative   
2     0     1           0                   0         0      negative   
3     1     0           0                   0         0      negative   
4     1     0           0                   0         0      negative   

  age_60_and_above  gender test_indication  
0             None  female           Other  
1             None  female           Other  
2             None    male           Other  
3             None  female           Other  
4             None    male           Other

### Unique values in each column

In [8]:
data.cough.unique()

array([0, 1, '0', '1', 'None'], dtype=object)

In [9]:
data.fever.unique()

array([0, 1, '0', '1', 'None'], dtype=object)

In [10]:
data.sore_throat.unique()

array([0, 1, '0', '1', 'None'], dtype=object)

In [11]:
data.shortness_of_breath.unique()

array([0, 1, '0', '1', 'None'], dtype=object)

In [12]:
data.head_ache.unique()

array([0, 1, '0', '1', 'None'], dtype=object)

In [13]:
data.corona_result.unique()

array(['negative', 'positive', 'other'], dtype=object)

In [14]:
data.gender.unique()

array(['female', 'male', 'None'], dtype=object)

In [15]:
data.age_60_and_above.unique()

array(['None', 'Yes', 'No'], dtype=object)

In [16]:
data.test_indication.unique()

array(['Other', 'Abroad', 'Contact with confirmed'], dtype=object)

### Combining the column that have '0' and 0 or '1' and 1 as different values

In [17]:
data.loc[data['cough'] == '0', 'cough'] = 0
data.loc[data['cough'] == '1', 'cough'] = 1
print(data.cough.unique())

[0 1 'None']


In [18]:
data.loc[data['fever'] == '0', 'fever'] = 0
data.loc[data['fever'] == '1', 'fever'] = 1
print(data.fever.unique())

[0 1 'None']


In [19]:
data.loc[data['sore_throat'] == '0', 'sore_throat'] = 0
data.loc[data['sore_throat'] == '1', 'sore_throat'] = 1
print(data.sore_throat.unique())

[0 1 'None']


In [20]:
data.loc[data['shortness_of_breath'] == '0', 'shortness_of_breath'] = 0
data.loc[data['shortness_of_breath'] == '1', 'shortness_of_breath'] = 1
print(data.shortness_of_breath.unique())

[0 1 'None']


In [21]:
data.loc[data['head_ache'] == '0', 'head_ache'] = 0
data.loc[data['head_ache'] == '1', 'head_ache'] = 1
print(data.head_ache.unique())

[0 1 'None']


### Replacing 'None' value with NaN

In [22]:
data.replace('None',np.nan,inplace=True)

In [23]:
data = data[data.corona_result != 'other']

In [24]:
data.corona_result.unique()

array(['negative', 'positive'], dtype=object)

### Dropping rows with unknown values in them

In [25]:
data.dropna(inplace=True) 

In [26]:
data.shape

(136294, 9)

## Using Label Encoding to handle categorical variables on  gender, age_60_and_above, test_indication and corona_result

In [27]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [28]:
print("Before: ", data['gender'].unique())

data['gender']= label_encoder.fit_transform(data['gender'])

print("After: ", data['gender'].unique())

Before:  ['male' 'female']
After:  [1 0]


In [29]:
print("Before: ", data['age_60_and_above'].unique())

data['age_60_and_above']= label_encoder.fit_transform(data['age_60_and_above'])

print("After: ", data['age_60_and_above'].unique())

Before:  ['Yes' 'No']
After:  [1 0]


In [30]:
print("Before: ", data['test_indication'].unique())

data['test_indication']= label_encoder.fit_transform(data['test_indication'])

print("After: ", data['test_indication'].unique())

Before:  ['Other' 'Abroad' 'Contact with confirmed']
After:  [2 0 1]


In [31]:
print("Before: ", data['corona_result'].unique())

data['corona_result']= label_encoder.fit_transform(data['corona_result'])

print("After: ", data['corona_result'].unique())

Before:  ['negative' 'positive']
After:  [0 1]


In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 136294 entries, 122808 to 265120
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   cough                136294 non-null  float64
 1   fever                136294 non-null  float64
 2   sore_throat          136294 non-null  float64
 3   shortness_of_breath  136294 non-null  float64
 4   head_ache            136294 non-null  float64
 5   corona_result        136294 non-null  int32  
 6   age_60_and_above     136294 non-null  int32  
 7   gender               136294 non-null  int32  
 8   test_indication      136294 non-null  int32  
dtypes: float64(5), int32(4)
memory usage: 8.3 MB


### Saving the dataframe to csv

In [33]:
data.to_csv("covidpred-preprocessed.csv")